[package]
name = "zbustest"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
zbus = "3.15"
zbus_macros = "3.15"
serde = { version = "1.0", features = ["derive"] }
futures-util = "0.3"
