[package]
name = "zbustest"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
ksni = "0.3.3"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
zbus = "5.13.2"
